[theme]
base            = "dark"
backgroundColor = "#060608"
secondaryBackgroundColor = "#0C0C10"
textColor       = "#EDE5D0"
font            = "sans serif"

[server]
headless        = true
enableCORS      = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false